title: Awesome site
author: Kevin McElfresh
email: kevin_mcelfresh@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  This site is so awesome
theme: minima
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
